config/routes.rb
Spree::Core::Engine.routes.draw do
  
  #mount StripeEvent::Engine, at: '/subscription/web-hooks' # provide a custom path
  
  namespace :admin do
    
    resources :products do
      resources :plans do
      	collection do
   		  post :update_positions
   		end
   	  end
    end
  end
end

app/models/spree/plan.rb
module Spree
  class Plan < Spree::Base
  	acts_as_paranoid

  	belongs_to :variant
  	belongs_to :payment_method
    #has_many :subscriptions
    validates_uniqueness_of :variant_id, scope: :payment_method_id, allow_blank: false, conditions: -> { where(deleted_at: nil) }
    
    before_create :create_plan
    before_save :update_plan, unless: :new_record?
    before_destroy :delete_plan

    INTERVAL = { week: 'Weekly', month: 'Monthly', year: 'Annually' }
    CURRENCY = { cad: 'CAD'}
	
		def deleted?
      !!deleted_at
    end
    def requires_redirect?
    	provider.requires_redirect?
    end
    def description_or_default
    	self.description || "Subscription"
    end

    def raise_invalid_order_error(order)
      raise "Not a valid order." unless order.is_a?(Spree::Order) && order.has_subscription?
    end
    def build_customer_profile(order)
    	raise_invalid_order_error(order)
    	return provider.create_customer_profile(order,self)
    end
    def subscribe(order)
	    raise_invalid_order_error(order)
	    # pass the order so the provider can get the customer (if necessary), and the plan for the plan_api_id
	    provider.subscribe(order, self)

	    #OK, so we successfully subscribed.
	    # begin
	    #   #Now let's record the credit card
	    #   byebug
	    #   payment_method = 
	    #   customer = @subscription.user.find_or_create_stripe_customer()
	    #   card = customer.cards.first  
	    #   spree_card = Spree::CreditCard.find_by(:gateway_payment_profile_id=>customer.cards.first.id)
	    #   if(spree_card.nil?)
	    #     Spree::CreditCard.create(
	    #           month: card.exp_month,
	    #           year: card.exp_year,
	    #           cc_type: 'master',
	    #           last_digits: card.last4,
	    #           name: card.name,
	    #           payment_method_id: 1, #Need to work on this one
	    #           gateway_customer_profile_id: customer.id,
	    #           gateway_payment_profile_id: customer.cards.first.id,
	    #           user_id: spree_current_user.id
	    #         )
	    #   end 
	    # rescue => e
	    #   #Just catch everything and log
	    #   logger.error e.message
	    #   e.backtrace.each { |line| logger.error line }
	    # end
	  end

	  def unsubscribe(order, subscription)
	    raise_invalid_order_error(order)
	    # pass the order so the provider can get the customer (if necessary), and the plan for the plan_api_id
	    provider.unsubscribe(order, subscription)
	  end

	  def provider
	  	self.payment_method
	  end
	  def create_plan
	  	set_api_plan_id
	  	provider.create_plan(self)
	  end
	  def update_plan
	  	provider.update_plan(self)
	  end
	  def delete_plan
	  	provider.delete_plan(self)
	  end

	  private

      def set_api_plan_id
        provider.set_api_plan_id(self)
      end
  end
end

app/controllers/spree/admin/plans_controller.rb
module Spree
  module Admin
    class PlansController < ResourceController
      belongs_to "spree/product", :find_by => :slug
      before_action :load_data, only: [:new, :create, :edit, :update]
      
      # def index
      #   #@plans = @product.plans

        
      # end
      def new
        @plan = Spree::Plan.new
        
      end

      protected
        #

      def permitted_resource_params
        params.require(:plan).permit(permitted_plan_attributes)
      end

      def permitted_plan_attributes
        [:variant_id,:payment_method_id,:name]
      end

      def collection
        @deleted = (params.key?(:deleted) && params[:deleted] == "on") ? "checked" : ""

        if @deleted.blank?
          @collection ||= super
        else
          @collection ||= Plan.only_deleted.includes(:variant).where(spree_variants: {:product_id => parent.id})
        end
        @collection
      end

      private
      def load_data
        @payment_methods = []
        Spree::PaymentMethod.all.each do |method|          
          @payment_methods << method if method.subscriptions_supported?
        end
        @variants = @product.variants
      end
      
    end
  end
end

app/views/spree/admin/plans/_form.html.haml
.label-block.alpha{"data-hook" => "admin_plan_form_fields"}
  .row
    .three.columns{"data-hook" => "plans"}
      .field{"data-hook" => "variant"}
        = f.label :variant_id, Spree.t(:variant) 
        = f.collection_select(:variant_id, @variants, :id, :sku, { }, { :class => 'select2 fullwidth' }) 
    .three.columns{"data-hook" => "plans"}
      .field{"data-hook" => "payment_method"}
        = f.label :payment_method_id, Spree.t(:payment_method)
        = f.collection_select(:payment_method_id, @payment_methods, :id, :name, { }, { :class => 'select2 fullwidth' }) 
    .four.columns{"data-hook" => "plans"}
      .field{"data-hook" => "name"}
        = f.label :name, Spree.t(:name)
        = f.text_field :name, :class => 'fullwidth'      
  .row
    .ten.columns
      .field{"data-hook" => "description"}
        = f.label :description, Spree.t(:description)
        = f.text_area :description, :class => 'fullwidth'      
.clear

app/views/spree/admin/plans/edit.html.haml
= render :partial => 'spree/admin/shared/product_sub_menu'

= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Plans' } 

= render :partial => 'spree/shared/error_messages', :locals => { :target => @plan }
= form_for [:admin, @product, @plan] do |f|
  %fieldset{"data-hook" => "admin_plan_new_form"}
    %legend{:align => "center"}= Spree.t(:update_plan)
    = render :partial => 'form', :locals => { :f => f }
    = render :partial => 'spree/admin/shared/edit_resource_links'

app/views/spree/admin/plans/index.html.haml
= render :partial => 'spree/admin/shared/product_sub_menu'
= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Plans'}
%fieldset{"data-hook" => "admin_plans"}
  %legend{:align => "center"}= Spree.t(:plans)
  #new_plan
  - if @plans.any?
    %table.index.sortable{"data-sortable-link" => "#{update_positions_admin_product_plans_path(@product)}"}
      %colgroup
        %col{:style => "width: 25%"}/
        %col{:style => "width: 25%"}/
        %col{:style => "width: 16.5%"}/
        %col{:style => "width: 16.5%"}/
        %col{:style => "width: 16.5%"}/
      %thead{"data-hook" => "variants_header"}
        %tr
          %th= Spree.t(:variant)
          %th= Spree.t(:payment_method)
          %th= Spree.t(:name)
          %th= Spree.t(:payment_method_plan_id)
          %th.actions
      %tbody
        - @plans.each do |plan|
          %tr{:id => "#{spree_dom_id plan}", :style=> "#{'color:red;' if plan.deleted?}", 'data-hook'=>"plan_row", :class=>"#{cycle('odd', 'even')}"}
            %td= plan.variant.sku
            %td.align-center= plan.payment_method.name
            %td.align-center= plan.name
            %td.align-center= plan.api_plan_id
            %td.actions
              = link_to_edit(plan, :no_text => true) unless plan.deleted?
              = link_to_delete(plan, :no_text => true) unless plan.deleted?
        - unless @product.has_variants?
          %tr
            %td{:colspan => "5"}= Spree.t(:none)
  - else
    .alpha.twelve.columns.no-objects-found
      -if @deleted.blank?
        = succeed(', ') do
          = Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/plans'))
        = succeed('!') do
          =link_to Spree.t(:add_one), spree.new_admin_product_plan_path(@product)
      -else
        = Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/plans'))
  - if @product.empty_option_values?
    %p.first_add_option_types.no-objects-found{"data-hook" => "first_add_option_types"}
      = Spree.t(:to_add_variants_you_must_first_define)
      = link_to Spree.t(:option_types), admin_product_url(@product)
      = Spree.t(:and)
      = link_to Spree.t(:option_values), admin_option_types_url
  - else
    - content_for :page_actions do
      %ul.inline-menu{"data-hook" => "toolbar"}
        %li#new_var_link{"data-hook" => ""}
          = link_to_with_icon('plus',                 |
             Spree.t(:new_plan),                      |
             new_admin_product_plan_url(@product),    |
             :'data-update' => 'new_plan',            |
             :class => 'button'                       |
            )                                         |
        %li= link_to_with_icon('filter', @deleted.blank? ? Spree.t(:show_deleted) : Spree.t(:show_active), admin_product_plans_url(@product, :deleted => @deleted.blank? ? "on" : "off"), :class => 'button')

/ = render :partial => 'spree/admin/shared/product_sub_menu'
/ = render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => "Subscriptions"}
/ - if @product.has_variants?
/   - for variant in @product.variants_including_master do
/     = render 'form', :variant => variant
/ - else
/   This product has no variants.
/   = render 'form', :variant => @product.master

app/views/spree/admin/plans/new.html.haml
= render :partial => 'spree/admin/shared/product_sub_menu'

= render :partial => 'spree/admin/shared/product_tabs', :locals => { :current => 'Plans' } 

= render :partial => 'spree/shared/error_messages', :locals => { :target => @plan }
= form_for [:admin, @product, @plan] do |f|
  %fieldset{"data-hook" => "admin_plan_new_form"}
    %legend{:align => "center"}= Spree.t(:new_plan)
    = render :partial => 'form', :locals => { :f => f }
    = render :partial => 'spree/admin/shared/new_resource_links'